📈 Stat 📈
siyoga/warehouse pull request #12
Opened 2023-12-30 18:16 UTC by Krenras

Написал сервис статистики. Он работает на логической репликации PostgresSQL.
(https://postgrespro.ru/docs/postgresql/14/logical-replication).

Через setup-db.sh меня уровень wal-записей на logical и создаю публикации в сервисах ai и user для всех таблиц которые будут добавлены. После этого на сервисе статистики я создаю подписки на 2 эти публикации после создания gorm-ом такого же набора таблиц, как и в сервисах, на которые я подписался. Должны повторяться названия таблиц и названия всех полей, но в базе-подписчике они могут быть с дополнительными полями. Хочу переместить поля с подсчетом количества использований нейронки, и так далее(всё что нужно трекать в статистике).

Пока не понимаю как отслеживать время использования конкретной нейронки конкретным пользователем и статус активности пользователя.

Новый env-файл кину тебе в телеге.

2023-12-31 06:31 UTC, siyoga requested changes
В целом, к бизнес-логике у меня нет претензий она простая и понятная. Есть косяки, которые я попросил исправил.

Оставил также комментарии к TODO куда стоит посмотреть/подумать.

2023-12-31 06:31 UTC, siyoga commented on services/stat/cmd/dataservice/main.go
> +func CreateSub(c config.DatabaseCfg, db *gorm.DB) *e.DBError {
Функцию стоит сделать локальной, ты её используешь только здесь.

2023-12-31 06:31 UTC, siyoga commented on services/stat/cmd/dataservice/main.go
> +}
Стоит ли переносить эту логику в отдельную функцию? Ты её планируешь переиспользовать потом?

2023-12-31 06:31 UTC, siyoga commented on services/stat/cmd/dataservice/main.go
> +	}
Здесь нам не нужно логировать ошибку, т.к. это код отвечающий за подготовку окружения для сервиса - мы сразу можем выбрасывать панику в случае ошибки.

2023-12-31 06:31 UTC, siyoga commented on services/stat/cmd/dataservice/main.go
> +func NewStatDatabase(logger *logrus.Logger) *statdata.Database {
Логгер убрать из аргументов

2023-12-31 06:31 UTC, siyoga commented on services/stat/cmd/server/main.go
> +	//Todo: сделать ручки для принятия проведённого времени на сайте конкретным порльзователем
У меня есть идея, как это можно сделать с помощью сессий. Это надо обсудить.

2023-12-31 06:31 UTC, siyoga commented on services/stat/cmd/server/main.go
> +	//Todo: сделать ручку увеличения количества просмотров каждой нейронки
Она уже есть в AI сервисе

2023-12-31 06:31 UTC, siyoga commented on services/stat/cmd/server/main.go
> +	//Todo: перенести логику трекинга количества использований каждой нейронки сюда
То же самое, что и на 19 строке

2023-12-31 06:31 UTC, siyoga commented on services/stat/cmd/server/main.go
> +	//Todo: перенести логику трекинга количества использований каждой нейронки сюда
Это все можно сделать через мидлвари + grpc - это надо обсуждать

2023-12-31 06:31 UTC, siyoga commented on services/stat/dataservice/statdata/operations.go
> +func (pvd *Database) GetNumOfUsers() (uint, *e.DBError) {
Замени `pvd` на просто `d`

2023-12-31 06:31 UTC, siyoga commented on services/stat/dataservice/statdata/operations.go
> +func (pvd *Database) GetNumOfUsers() (uint, *e.DBError) {
И во всех остальных функциях тоже

2023-12-31 06:31 UTC, siyoga commented on services/stat/dataservice/statdata/operations.go
> +// }
Убрать

2023-12-31 06:31 UTC, siyoga commented on services/stat/model/ai.go
> +// TODO: Подумать над синхронизацией с сервисом пользователей.
Если тебе нужна синхронизация между разными БД - посмотри, что такое распределенные транзакции. Для завтравочки - https://habr.com/ru/articles/769102/. В частности углубись в паттерн SAGA

Реализацию на нашем примере, можешь найти в:
[Функция регистрации](https://github.com/siyoga/warehouse/blob/a002c631ce31c8212ad372cdf685ce72329725e6/services/auth/service/register/register.go#L82-L120)
[Функции отката изменений](https://github.com/siyoga/warehouse/blob/a002c631ce31c8212ad372cdf685ce72329725e6/services/auth/adapter/broker/operations.go#L44-L68)

2023-12-31 06:31 UTC, siyoga commented on services/stat/service/ai.go
Добавить Unit-тесты

2023-12-31 06:31 UTC, siyoga commented on services/stat/service/user.go
Добавить Unit-тесты

2023-12-31 06:31 UTC, siyoga commented on services/user/model/user.go
> +	ViaGoogle bool           `json:"via_google:omitempty" gorm:"default:false;not null"`
Верни точку с запятой. Будет некорректно работать gorm

`json:"via_google";omitempty`

2023-12-31 06:31 UTC, siyoga commented on setup-db.sh
Тут все норм. Но потом попрошу это все переделать в миграции, как подготовлю примеры сам

2024-01-03 15:23 UTC, Krenras commented on services/stat/cmd/server/main.go
> +	//Todo: сделать ручки для принятия проведённого времени на сайте конкретным порльзователем
Трэкать число истёкших сессий и умножать на их продолжительность?

2024-01-03 15:26 UTC, Krenras commented on services/stat/cmd/server/main.go
> +	//Todo: сделать ручку увеличения количества просмотров каждой нейронки
Я хочу всё, что связанно со статистическими данными перенести сюда, соответственно, я хочу убрать поле количества использований с сервиса AI и перенести его сюда с добавлением ручки для его изменения.

2024-01-03 16:13 UTC, siyoga commented on docker-compose.yml
> +    depends_on:
Надо посмотреть, вроде бы работало. Может косяк в синтаксисе баша из-за чего не работает код.

2024-01-03 16:14 UTC, siyoga commented on services/stat/cmd/server/main.go
> +	//Todo: сделать ручку увеличения количества просмотров каждой нейронки
Понял, услышал.

2024-01-03 16:16 UTC, siyoga commented on services/stat/cmd/server/main.go
> +	//Todo: сделать ручки для принятия проведённого времени на сайте конкретным порльзователем
Как один из вариантов, можно сделать и так, либо на каждой ручке смотреть сколько прошло времени с момента создания сессии и добавлять к общему кол-ву.

2024-01-03 17:17 UTC, Krenras commented on services/stat/cmd/server/main.go
> +	//Todo: сделать ручки для принятия проведённого времени на сайте конкретным порльзователем
А на фронте это трэкать нельзя?

2024-01-03 17:19 UTC, Krenras commented on docker-compose.yml
> +    depends_on:
Я когда хотел логику сетапа БД в одном сшнике реализовать много панькался с этим, поэтому пробовал это всë

2024-01-03 17:31 UTC, Krenras commented on docker-compose.yml
> +    depends_on:
https://docs.docker.com/config/containers/multi-service_container/#run-multiple-processes-in-a-container

Вот про эту штуку из доки

2024-01-05 18:07 UTC, siyoga approved these changes
Гуд, спасибо Кирюха

2024-01-05 18:07 UTC, merged